### ISSUE TITLE
Flint doesn't find or parse JSX dependencies

### ISSUE THREAD

**Issue by appsforartists** [flintjs/flint#213]
If I try to use a NPM module with this shape:

```
// in ComponentB.jsx:

var ComponentA = require("./ComponentA");
```

Flint can't find it, because it doesn't search for .jsx files.

**Comment by appsforartists** [comment]
Simply changing the extension doesn't fix it either; Flint doesn't understand JSX in dependencies.

**Comment by natew** [comment]
Good ticket, we are getting we pack to be better overall this is an important one. Eventually we want to allow custom config here

**Comment by natew** [comment]
@appsforartists Happy new year!

Can I ask what the use case is here?

One thing I haven't thought too much about actually is dropping in individual `React.createClass` style jsx files and using them, which I'm assuming is it.

Right now our build system does this for "exported" files (that are later imported):

- Run Flint preprocess
- Run babel
- Run Flint postprocess
- Detect exported: true => Send to webpack as raw JS (skip rest)
- ...

In order to support this we'd need to instead:

- Run Flint preprocess
- Detect exported: true => send to webpack (skip rest)
- Run babel
- Run postprocess

Then we'd have to setup the babel loader separately into Webpack. Not going much deeper for now until I get some feedback, cc @ncammarata

**Comment by natew** [comment]
Added really basic support for this (in that if it sees .jsx, it will run it though a vanilla babel-loader).

This definitely adds some ugly weight to the whole deal (two babels running), but for now can be used to test it out.

https://github.com/flintjs/flint/commit/fa805224f991dc4fb6b1ba3d77d381d6158d83af

**Comment by natew** [comment]
This should work now! We don't do JSX but it will run full on React apps! See: https://flintjs.com/transition
