### ISSUE TITLE
optional (or mandatory) .jsf 

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#54]

**Comment by natew** [comment]
Added

**Comment by liron00** [comment]
Is there any chance I can convince you guys to consider .js files with Flint code to be invalid?

**Comment by liron00** [comment]
Arguments:

1. There's no precedent for a third-party team expanding the range of acceptable contents for a given file extension.

2. If .js can be Flinty, then we can't use .js to imply "Here's a JS file that *isn't* flint-specific", or "Here's a JS file that isn't about Views".

3. The .js extension would also be useful to represent "This file has Views in it but we've compiled the Flint-specific syntax out so it's regular JS now."

**Comment by liron00** [comment]
4. In the chrome debugger, whenever I see .js, I assume I'm looking at a sloppy compiled version of my views. I'm always surprised to see my source-mapped Flint code instead.

**Comment by natew** [comment]
I'd say something like this should come down a sort of poll. Perhaps once we launch we could get more feedback.  As counter points:

1. A lot of React dev's use `.js` even when using JSX, because JSX is considered an extension, and I'd consider Flint one as well

2. Given we consider Flint a "future JS polyfill" it helps us send that message

Granted, not strongly held views, but I'd like to see more comments here on it.

**Comment by ncammarata** [comment]
I think launching with .js is good to push the idea that they can use normal JS. Forever ago I had .jsf and when I showed people they felt like they were in a foreign programming language. Additionally, there aren't really *non JS* files, because if a file doesn't use a view, our compiler just outputs it normally.

Six months from now when people know what Flint is more, I think we should consider .jsf the default

**Comment by liron00** [comment]
Okay
